encoding: utf-8

env: production

exclude: ['buildspec.yml','package-lock.json','Gemfile', 'Gemfile.lock', 'Gruntfile.js', 'package.json', 'readme.md', 'README.md', 'sftpCache.json' ,'node_modules','armydotmil.github.io' ]
    
plugins:
  - octopress-minify-html
  - jekyll-last-modified-at
  
sass:
  sass_dir: _scss
  style: compressed

title: Core-Support

jekyll-minifier:
  exclude: ['*.html','*.css','*.scss']
