# Any Comments:

  - title: Page Settings
    articles:
      - subtitle: Page settings
        sections:
          - sectiontitle: 
            para1: You can use Page Settings to edit a page's title, logo, social media accounts, and other options. This reference guide walks you through the universal settings available on all Pages.
          - sectiontitle: Access your Page settings
            numlist:
              - listname: 
                one: Click on <strong>Page</strong> from the main menu.
                two: From your <strong>Edit Page</strong> screen, locate your settings in the sidebar menu on the right side of your screen.
                three: Click the arrow located in the top-right corner of your Page’s action toolbar to show and hide the settings. This will slide the drawer out of view, allowing you to see a preview of your page content.
                four: Make any changes to your settings in the Basic Information, Customize SEO, Connect to Social Media, and Advanced Options sections. To learn more, see the chart below.
                five: Click <strong>Publish</strong> in the top-right corner of the action bar, to publicly release changes to <a class="underline-link" href="https://www.army.mil">www.army.mil</a>. 
          - sectiontitle: Page Overview
            para1: The information in the overview section cannot be modified by publishers or administrators.
            lexicon:
              - title: Page Status
                definition: Refers to the publish state on <a class="underline-link" href="https://www.army.mil">www.army.mil</a> (Draft, Updates Pending, Published or Deactivated)
              - title: Last Update
                definition: Date and time of the last action
              - title: Organization
                definition: The CORE organization that owns this Page.
              - title: Page URL
                definition: The exact web address for your Page. If you want to change your Page URL, please submit a request to the <a class="underline-link" href="mailto:usarmy.pentagon.hqda-ocpa.mbx.army-core@mail.mil?subject=Request Page URL Change">CORE Support Team</a>.
            hr: 
          - sectiontitle: Basic Information
            lexicon:
              - title: Page Title
                definition: The title displayed on the Page header. It is typically your organization’s abbreviation.
              - title: Page Subtitle
                definition: This is an optional subtitle or tagline displayed beneath the Page title in the header. This is typically your organization’s full name.
              - title: Contact Email Address	
                definition: The email address is used on the Contact Us link in your Page footer. This email will be publicly accessible, so we recommend using an organization mailbox, instead of a personal email.
              - title: Header Logo
                definition: Add an organization logo to your Page header. To learn more, visit <a class="underline-link" href="./page_logo.html">Customize your Page logo</a>.
            hr: 
          - sectiontitle: Customize SEO Metadata
            lexicon:
              - title: Page Title
                definition: The SEO title appears in browser address bars, search engine results, and sometimes in social shares.
              - title: SEO Description
                definition: The text appears below a page title/link in search engine results and in social shares. Also called page meta description.
            note: Visitors read these titles and descriptions to decide if they want to click on your web page in search results and on social media. To make your site inviting, we recommend that you make your metadata short, readable and informative. Incorporate relevant keywords to improve your SEO, but avoid cramming your descriptions with keywords in a way that doesn't form cohesive sentences. For more SEO tips, visit <a class="underline-link" href="../../best-practices/co/search_engine_optimization.html">Search Engine Optimization</a>.
            hr: 
          - sectiontitle: Connect to Social Media
            lexicon:
              - title: Social Media
                definition: Add your organization’s social media accounts. Icons for these platforms appear in your Page header and footer, allowing your audience to connect with you via other digital platforms. To learn more, visit <a class="underline-link" href="./social_media.html">Customize your social media accounts</a>.
            hr: 
          - sectiontitle: Advanced Options
            lexicon:
              - title: Google Analytics Tracking ID
                definition: Add a Google Analytics tracking ID to dive deeper into Page metrics. This will allow you to track data such as traffic-referral information, user characteristics and browsing information directly from your organization’s Google Analytics account. To learn more, visit <a class="underline-link" href="./connect_page_to_google_analytics.html">Connect your Page to Google Analytics</a>.
